# kind: VirtualService
# apiVersion: networking.istio.io/v1alpha3
# metadata:
#   name: fleetman-vehicle-telemetry
#   namespace: default
# spec:
#   hosts:
#     - fleetman-vehicle-telemetry
#   http:
#     - fault:
#         abort:
#           httpStatus: 503
#           percentage:
#             value: 10
#       route:
#         - destination:
#             host: fleetman-vehicle-telemetry

# kind: DestinationRule
# apiVersion: networking.istio.io/v1
# metadata:
#   namespace: default
#   name: fleetman-vehicle-telemetry
#   labels:
#     kiali_wizard: traffic_shifting
#   annotations: ~
# spec:
#   host: fleetman-vehicle-telemetry.default.svc.cluster.local
#   trafficPolicy: ~

---
kind: VirtualService
apiVersion: networking.istio.io/v1
metadata:
  namespace: default
  name: fleetman-vehicle-telemetry
  labels:
    kiali_wizard: traffic_shifting
spec:
  http:
  - route:
    - destination:
        host: fleetman-vehicle-telemetry.default.svc.cluster.local
      weight: 10
  hosts:
  - fleetman-vehicle-telemetry.default.svc.cluster.local