---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bookshop-me-tls
spec:
  secretName: bookshop-me-tls
  duration: 2160h
  renewBefore: 360h
  commonName: bookshop.me
  dnsNames:
    - bookshop.me
    - www.bookshop.me
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: adwiza@gmail.com
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - http01:
        ingress:
          ingressClassName: istio
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: adwiza@gmail.com
    privateKeySecretRef:
      name: letsencrypt-issuer-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: istio