apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: istio-default-gateway
  namespace: istio-ingress
  # annotations:
    # metallb.io/address-pool: local
    # loadBalancerIP: 192.168.3.12
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
      - "*.local"
      - "*.me"
  - port:
      number: 9001
      name: tcp-9001
      protocol: TCP
    hosts:
        - "*.local"
        - "*.me"
