apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: istio-default-gateway
  namespace: istio-ingress
  annotations:
    kubernetes.io/tls-acme: "true"
spec:
  selector:
    istio: ingressgateway
  servers:
    - hosts:
        - "*.local"
        - "*.me"
      port:
        number: 80
        name: http
        protocol: HTTP
    #   tls:
    #     httpsRedirect: false
    # - hosts:
    #     - "*.local"
    #     - "*.me"
    #   port:
    #     name: https
    #     number: 443
    #     protocol: HTTPS
    #   tls:
    #     credentialName: bookshop.me
    #     mode: SIMPLE
    - hosts:
        - "*.local"
        - "*.me"
      port:
        number: 9000
        name: tcp-9000
        protocol: TCP
    - hosts:
        - "*.local"
        - "*.me"
      port:
        number: 9001
        name: tcp-9001
        protocol: TCP
    - hosts:
        - "*.local"
        - "*.me"
      port:
        number: 8123
        name: tcp-8123
        protocol: TCP
    - hosts:
        - "*.local"
        - "*.me"
      port:
        number: 5432
        name: tcp-5432
        protocol: TCP