apiVersion: v1
kind: Secret
metadata:
  name: nxrm-ha-dbsecret
  namespace: nexus
stringData:
  db-name: mydatabase
  db-host: postgres.local
  db-user: admin
  db-password: mypassword
type: Opaque
---
apiVersion: v1
kind: Secret
metadata:
  name: nxrm-ha-adminsecret
  namespace: nexus
stringData:
  nexus-admin-password: nexus
type: Opaque
