---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: bookinfo
spec:
  hosts:
  - "bookshop.local"
  - "bookshop.me"
  gateways:
  - istio-ingress/istio-default-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: nginx-service.default.svc.cluster.local
        port:
          number: 80
---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  hosts:
  - "longhorn-ui.local"
  gateways:
  - istio-ingress/istio-default-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: longhorn-frontend
        port:
          number: 80
# ---
# apiVersion: networking.istio.io/v1alpha3
# kind: VirtualService
# metadata:
#   name: postgres
# spec:
#   hosts:
#   - "bookshop.me"
#   gateways:
#   - istio-ingress/istio-default-gateway
#   http:
#   - match:
#     - uri:
#         prefix: /
#     route:
#     - destination:
#         host: postgres-service.default
#         port:
#           number: 5432
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: minio-external
spec:
  hosts:
    - minio.local
  location: MESH_EXTERNAL
  ports:
    - number: 9001
      name: http
      protocol: HTTP
  resolution: NONE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: mlflow
  namespace: mlflow
spec:
  hosts:
    - "mlflow.local"
  gateways:
    - istio-ingress/istio-default-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: mlflow.mlflow.svc.cluster.local
            port:
              number: 80